### ISSUE TITLE
update ncbi annotation transfer to use pre-built alignments

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#134]
ncbi.py tbl_transfer currently takes a pair of fasta files and pairwise aligns them.

Create a new command in ncbi.py: tbl_transfer_prealigned, that does the same thing as tbl_transfer, but instead of taking two fasta files as input, it takes pre-made alignments as input and also takes as input the name of the reference sequence and the name of the alternate sequence in the alignment.  The input alignment may contain more than these two sequences, but the other sequences will be ignored.

Also update the Snakemake rule (rule annot_transfer in interhost.rules) accordingly.

This depends on #127 .

**Comment by tomkinsc** [comment]
ncbi.py has been updated in 4aab78ecbdb8ef3a096f87500892987101629b7a to include `tbl_transfer_prealigned`, but it's unclear to me how the snakemake rule will make use of it. The rule can get the reference sequence name from the reference fasta file (as specified in the config), but how will it know the name of the alternate sequence? During the [transposition step](https://github.com/broadinstitute/viral-ngs/blob/master/interhost.py#L82) of a mafft multialignment, the relationship of sample->{seq1, seq2, seq3} is lost, since the mafft alignment creates a separate output fasta file for each chromosome. Should we be including the sample name in the sequence ID as part of the transposition step, or otherwise tracking the relationship?

**Comment by dpark01** [comment]
So, as I look at what NCBI wants as a batch submission, I'm realizing that the current code creates one tbl file per sample, but I think we will need to actually create one tbl file per sample per chromosome...

We had discussed earlier about how the config.json is going to need to have a new variable that indicates the number of chromosomes per genome.  Snakemake rules can then split out multiple files if necessary for certain steps, or pass the number as a parameter to a script that needs to be told that number.
