### ISSUE TITLE
possible bug in VPhaser2 variant percentage calculation

### ISSUE THREAD

**Issue by harper357** [broadinstitute/viral-ngs#152]
I was using the viral-ngs on the command line to use viral-ngs/intrahost.py vphaser_one_sample when I noticed what I think might be a bug in the calculation of the variant percentage. 

When V-Phaser2 says there is two SNPs at the same location, the Var_percent column seems to the sum of the percents of the variants. Was this intended? Below is an example of what I am talking about :

1275	A	G	0.02322	snp	0.400866	G:5009:7414:1	A:6:24:1	T:13:7:1

0.4% is not the percent of the variant called (in this case, A), but is instead the sum of both the A and T percents.

I tried to email the authors of VPhaser2, but both Xiao Yang's and M Zody's Broad Inst. emails seem to be no longer active and the google group appears to be dead.

**Comment by dpark01** [comment]
Hi @harper357 , thanks for asking about this. Always interesting to hear about people's use cases of the tools.

You're right that the V-Phaser authors have moved on, and the tool is no longer being maintained / supported. The google group actually appears to be orphaned--no one (including Xiao or Zody) have ownership/admin rights anymore (because their owning email accounts are dead). The viral-ngs project adopted V-Phaser2 when V-Phaser2 was still and active project. It's possible that if we run into problems with it in the future, we may swap it out for a different tool.

The output format of V-Phaser2 does have limitations. For example, while you suggest it might be a bug that the reported percentage is the sum of the minor allele frequencies, it's not clear what else that value should be without breaking the file format. Personally, I also interpret "minor allele frequency" to mean "sum of non-major allele frequencies" (meaning the value could easily be above 50% if there's many alleles), so I think it's doing a sensible thing in this case.

In any case, this viral-ngs package ignores that column in V-Phaser's output: we only look at the numeric read counts in the other columns and recalculate the frequencies ourselves (this is partly because we apply our own filters on top of V-Phaser's usual filters). If you are parsing V-Phaser's raw output, I recommend taking this approach as well.

There are far worse issues in the V-Phaser output format that make certain scenarios very awkward to describe (requiring two rows of output sometimes... Ebola's GP slippage site is a good example of this). The viral-ngs wrapper scripts attempt to handle those as sensibly as possible and convert everything to VCF, which should be much easier for users to deal with. Let us know if the VCF output of the viral-ngs package is not behaving as expected on your data. Note that in the past few days, we recently made a few changes in this area that should allow it to function more appropriately for a broader range of viruses.
