### ISSUE TITLE
problem with pre-install of the external tools

### ISSUE THREAD

**Issue by sbecuwe** [broadinstitute/viral-ngs#247]
Hello,

I have a problem running "nosetests -v test.unit.test_tools". For muscle, I have to remove "-static" from the muscle's Makefile. For samtools, I have to modify both Makefile and htslib-1.2.1/Makefile because of a non-standard location of libz and libcurses on our system. Is there a way I can provide patch files to the install program? Or is there another way to deal with this kind of non-default setups? 

Thanks in advance!
Stefan

**Comment by sbecuwe** [comment]
Update: I found in the tools directory muscle.py and samtools.py. It was easy to fix muscle.py: I just needed the fix proposed for Mac OSX. I tried to do the same with samtools.py (see attachment). Compilation went fine. I only get an error at the end, but don't have a clue why installation would have failed, even when using nosetests --nocapture. 

```
======================================================================
FAIL: test.unit.test_tools.TestToolsInstallation.testAllToolInstallers(<class 'tools.samtools.SamtoolsTool'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "[...]/python3.5/site-packages/nose-1.3.7-py3.5.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "[...]/viral-ngs-1.3.5/test/unit/test_tools.py", line 37, in check_tool
    assert t.is_installed(), "installation of tool %s failed" % tool_class.__name__
AssertionError: installation of tool SamtoolsTool failed
```
Any suggestion to tackle this problem?

Thanks!
Stefan

[samtools_py.txt](https://github.com/broadinstitute/viral-ngs/files/206403/samtools_py.txt)

**Comment by tomkinsc** [comment]
Hi Stefan,

I'm sorry you've hit snags. Running viral-ngs under OSX is something we're still improving, but most aspects of viral-ngs should work. Since Mac environments tend to differ based on the packages users have installed via Homebrew/Macports (particularly compilers and libraries), and Xcode resources, there can be complications, like the one encountered with linking.

I recommend trying a [conda-based instal](https://viral-ngs.readthedocs.org/en/latest/install.html?highlight=gcc#tool-dependencies) of the viral-ngs tools. If you install [miniconda3](http://conda.pydata.org/miniconda.html), then run `nosetests -v test.unit.test_tools`, conda packages will be installed for many of the tools used by viral-ngs. Since anaconda.org distributes pre-built binaries, tools will install as quickly as you can download them, and without compilation. A few tools (Diamond, Kraken, Megan, tbl2asn,... ) are unavailable on OSX either due to RAM requirements (diamond, kraken) or missing source/Mac binaries (tbl2asn).

If it fits your use case, you might also try a [virtualized install](https://viral-ngs.readthedocs.org/en/latest/install.html#virtualized-installation-easy-deploy) of viral-ngs via virtualbox or AWS EC2.

**Comment by sbecuwe** [comment]
Hello Tom,

I'm installing viral-ngs on a Linux (RHEL) system, not on a Mac. I didn't make myself clear. Sorry for the confusion! 

We're using modules and dedicated directories for different packages. To get muscle installed on Linux, I could just use the fix that's in there for Mac OSX. So the only problem is samtools, although it compiles and the executable is there. Just wondering how to avoid the assert error mentioned above. When running run_all_tests.sh, it's also only samtools that produces an error.

**Comment by tomkinsc** [comment]
For RHEL I suggest trying a conda-based tool install as well. The samtools conda package is sourced from the [bioconda](https://github.com/bioconda/bioconda-recipes) channel, which currently builds binaries on CentOS 5 (fork of RHEL).

Otherwise, you might see if you can build [samtools](https://github.com/samtools/samtools) independent of viral-ngs. Samtools [depends](https://github.com/samtools/samtools/blob/develop/INSTALL) on ncurses and zlib, so you'll want to ensure those are installed on your system.

**Comment by sbecuwe** [comment]
As indicated, the problem is not about building samtools. I managed to change samtools.py such that it builds without problem. The executable is in viral-ngs-1.3.5/tools/build/samtools-1.2/samtools and it works. The only issue is at the end: 
```
AssertionError: installation of tool SamtoolsTool failed
```
As a result, run_all_tests.sh also produces many errors (only related to samtools). I don't see what to change in samtools.py to avoid the AssertionError.

**Comment by sbecuwe** [comment]
Found it! I removed the verifycmd since samtools has exit code 1 when not passing any options... Now also run_all_tests.sh is working (no errors)!
