### ISSUE TITLE
Add conda bin to $PATH at startup

### ISSUE THREAD

**Issue by yesimon** [broadinstitute/viral-ngs#288]
Lots of packages expect auxiliary bins in `$PREFIX/bin` and may call them with non-qualified bare executable names. Ideally the conda bin path should be prepended at some stage of startup. The only problem is that will force usage of conda python, and possibly a tighter integration where pip packages are also installed though conda. (This will be especially true for `pytest-cov`, which installs a `.pth` file to hook in subprocess coverage when the package is installed, which depends on which python is installing the patch).

**Comment by tomkinsc** [comment]
This needs to be part of a larger discussion about whether we want to require conda. @dpark01 

As it stands, conda is mostly optional, since we have fallback install methods for most tools. Requiring conda would obviate the need for the fallback install methods we have for all existing tools, at a potential loss of compiler optimizations for self-built tools and any `viral-ngs`-specific patches (are there any?). We're already adding and maintaining conda packages for some of our dependencies, so eliminating custom tool install methods would likely be a net gain for productivity since we wouldn't have to maintain the same tools in two places.

I tend to lean in favor of requiring conda, since it means we could distribute a common environment file that would encapsulate all (non-licensed) viral-ngs dependencies, including binaries and python packages. It would make installing viral-ngs easier, and likely faster. If we are concerned about issues upstream with bioconda, we could conceivably have a viral-ngs channel on anaconda.org for custom-built binaries. If we require conda to be on the `$PATH`, it solves the confusion related to having both conda and an active python virtual environment (i.e. Questions like: *What should the $PATH ordering be?* *Is the conda env activated prior to the Python virual env, or after? What about during env creation?*). 

We'd have to trust that conda will continue to be around, which is probably a safe bet.

**Comment by dpark01** [comment]
I'm intrigued by the possibilities... such as, could we utilize the py3 that's part of conda's payload and reduce our test matrix to a single version of python?

Within a few weeks I hope to put together a near-term dev roadmap. Feel free to lay out any desires as github issues and comment/upvote on them. Some priorities will be set more on user needs and project objectives, and some will include things that we see as easy wins on the infrastructural side.

**Comment by tomkinsc** [comment]
Closing this for now, since users are likely to either use the easy deploy script or otherwise know how to use conda.
