### ISSUE TITLE
Replace GATK with a tool under more permissive license

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#306]
Use of GATK is currently encumbered by a license that prohibits redistribution. We should consider replacing GATK with other tools that have more permissive licenses, so we can package viral-ngs for distribution as a Docker container, Amazon Machine Image (AMI), or conda package.

Currently, GATK is used mostly for variant calling. Possible replacements include [FreeBayes](https://github.com/ekg/freebayes) or [Platypus](http://www.well.ox.ac.uk/platypus), maybe [varscan](http://varscan.sourceforge.net/) (?). [snp-sites](https://github.com/sanger-pathogens/snp-sites)?

This depends on #305, since we'll need to evaluate the output quality of a different tool.

**Comment by tomkinsc** [comment]
It seems we are currently using two GATK tools: `IndelRealigner` and `UnifiedGenotyper `.

The `IndelRealigner` tool exists in the `gatk-framework` [conda package](https://bioconda.github.io/recipes/gatk-framework/README.html), which is derived from the MIT-licensed parts of GATK. We can simply install and use it. The `UnifiedGenotyper` tool is part of the restricted GATK. It may be work considering using `gatk-framework` for `IndelRealigner` and switching to something open (varscan?) to replace UnifiedGenotyper.

**Comment by biocyberman** [comment]
Maybe you guys can try to acquire a license/permission for redistribution. [GenomeStrip](http://software.broadinstitute.org/software/genomestrip/) apparently packs `Picard` and full `GATK` with their releases. 

Regarding the althernatives, human data I prefer `GATK`. I bump into it a lot, and it seems to be the best open source tool of its kind. Freebayes on the other hand has a more flexible way to handle ploidy setting. So, it may be worth to try FreeBayes. This needs a validation dataset to evaluate the results.

**Comment by dpark01** [comment]
It's been made quite clear by our legal office that GATK cannot be redistributed. GenomeStrip doesn't count because it is actually maintained, distributed, and supported as part of the GATK suite. Picard is not a problem since it's totally open source and free.

I agree I highly prefer GATK for it's usual use cases: calling variants from alignment data. However, the current viral-ngs package does not use GATK for it's normal use case, and only uses a tiny subset of its functionality when using reads to refine consensus assemblies. That's why it seems reasonable to replace it in this instance, but not without some regression testing.

Novoalign isn't bad because it allows for distribution of its free version through normal software distribution channels (like anaconda), and the only thing a user would need to do for viral-ngs is register a paid license file--and that's entirely optional.

**Comment by dpark01** [comment]
Hey so, [GATK4 is on BioConda](https://bioconda.github.io/recipes/gatk4/README.html). Maybe we should just try it and see if it works with minimal/no other changes on our part? That'd be a huge win from a usability point of view.

**Comment by dpark01** [comment]
Obviated by #743
