### ISSUE TITLE
make viral-ngs conda installable

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#310]
Creating a bioconda package for viral-ngs would greatly simplify installation in different environments and would allow for a straightforward offloading of dependency management as well.

This would require having our Tools look for their binaries in a different path in these cases.

**Comment by tomkinsc** [comment]
If we're packaging viral-ngs for distribution as a bioconda package, one issue is that the conda `meta.yaml` file does not allow us to specify optional dependencies or "extras". This means that if we list all tool packages as part of the viral-ngs `meta.yaml` file (analogous to a conda environment file), installation will fail on some platforms since not all packages are universally available and some dependencies will not be met. One workaround would be to specify tags for the dependencies to specify platforms where they are available (ex. `# [linux]`), but this isn't ideal since we'd have to keep the tags in sync with the current package list.

I might suggest the following:

> Conda package requirements include only Python (pip) packages, since binaries may not exist on all platforms. Python3 packages (Snakemake, etc.) are decorated with # [py3] so they are only installed on systems with an appropriate version of conda. Installing the viral-ngs conda package installs the contents of this git repo (sans `.git/`), and the pip dependencies.
> 
> The CondaPackage install method will check whether the environment variable `CONDA_DEFAULT_ENV` is populated. If so, it is used to determine the environment within which tools should be installed. The CondaPackage class will have a new method to return the flag for setting the environment (ex. "--name ENV") or (ex. "-p ENV_PATH"), based on whether it is a named env or an env path (absolute, so begins with a '/'). Fallback if `CONDA_DEFAULT_ENV` is not set (as in the case where a conda environment is not currently active for a given shell) is to do what we do now, and install tools in `tools/build/conda-tools/`. If conda install fails, fall back to our custom install methods (?).
> 
> With this system, each tool would install upon first use. A new file, `install_tools.py`, could enumerate tool classes and install each one. 
> 
> Instructions for installing viral-ngs would include installing miniconda, adding the bioconda channel, creating a new env for viral-ngs, activating the env, and installing the `viral-ngs` conda package. 

How does that sound?

**Comment by dpark01** [comment]
I think I have to dig in to understand conda mechanics better, but is there any reason that we can't just have the viral-ngs conda package list out the core dependencies for things that do exist on all platforms and python versions, just to get the easy and common things out of the way? E.g. Picard, samtools, novoalign, pip packages, etc.

Incidentally, the reason we had a full tool pre-install step (instead of just relying on on-demand) was only because of shared-file-system-HPC-Broad-like applications (which run into race conditions when a bunch of parallelized jobs all try to install missing tools at the same time). But I don't see why a cloud-based install would have any problem with on-demand-installing everything (in fact, it'd probably be more efficient since it would only install the absolutely necessary things).
