### ISSUE TITLE
parallelize blastn calls in taxon_filter.py

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#330]
The function `taxon_filter.py::`[`blastn_chunked_fasta()`](https://github.com/broadinstitute/viral-ngs/blob/master/taxon_filter.py#L696) should probably be parallelized, since passing `-num_threads` to `blastn` does not result in much concurrent processing.  [This thread](http://seqanswers.com/forums/showthread.php?t=5752) mentions the initial word matching by `blastn` is multi-threaded, while alignments are not, resulting in a lengthy sequential fraction in calls to `blastn` We're already chunking blastn input, so we should be able to process the chunks in parallel. This could be done via python `multiprocessing`, back-ported `concurrent-futures`, or maybe via a pre-fab concurrency context like [deco](https://github.com/alex-sherman/deco).

**Comment by dpark01** [comment]
Chunking and parallelizing variable-sized input is always an interesting game: you basically either go for a fixed number of chunks, or a fixed chunk size, or some combination that prefers one variable (e.g. # chunks) while placing a sane limit on min/max of the other (e.g. don't make them too small or large... or don't make too many or too few).

Our original chunking was fixed-chunk-size not for parallelization's sake, but to defend against non-linear memory and failure behaviors. If the idea is to parallelize execution, you might think that we might want to go for fixed # of chunks (because we theoretically know how many threads we want to spin up based on the instance size). But then, for the original memory reason, we also don't want those chunks to be too big, so you may need to enforce a min chunk size which may, in some scenarios, create a bunch more chunks.

And that leads to the idea that you probably won't just spin up all of the threads simultaneously, but you may want a job queue... in which case, maybe you actually just import snakemake APIs and invoke them directly? Or maybe we should be solving this problem at a higher level--in the pipelining code (snakemake rules, DNAnexus, etc).

**Comment by tomkinsc** [comment]
The optimal case is tricky, but we should be able to improve on the near-single-threaded performance we're seeing now. I'll put together an example pull request based on a fixed per-thread chunk size of (current max chunk size)/(number of threads), with (hopefully) sensible bounds on minimum chunk size and thread count.

Snakemake wouldn't really be ideal for queueing; the API isn't explicitly frozen, and we'd have to drop Py2 support. It would be nice if we could use a multi-threaded aligner that speaks bam natively, since we spend noticeable time on file conversion.

**Comment by tomkinsc** [comment]
Potential implementation in PR #331
