### ISSUE TITLE
Easy deployment script not creating viral-ngs directory

### ISSUE THREAD

**Issue by jrotieno** [broadinstitute/viral-ngs#483]
I have tried installing viral-ngs pipeline locally and while I expect three directories in viral-ngs-etc/, i.e. conda-env/, mc3/ and viral-ngs/, only the former two exist. This means that when I call on the command:

./easy-deploy-viral-ngs.sh create-project ABC 

I get the error:
Populating project directory...
cp: /Users/xxx/viral-ngs-etc/viral-ngs/pipes/config.yaml: No such file or directory
cp: ../../viral-ngs/pipes/Snakefile: No such file or directory
Project created: /Users/xxx/viral-ngs-etc/projects/ABC
OK

Something i'm doing wrong or the install script has an error?

**Comment by tomkinsc** [comment]
Hi James, you need to initialize the environment first via:
`./easy-deploy-viral-ngs.sh setup`
The `create-project` command merely creates named directories to store data files, with a few files copied in from the viral-ngs folder (which is why it would complain if you haven't run `setup` first), along with placeholder files for running the snakemake workflow.

**Comment by jrotieno** [comment]
Hi Tom, the error I got was actually after running the set up command.

**Comment by tomkinsc** [comment]
Try removing your `./viral-ngs-etc/` directory and re-running`./easy-deploy-viral-ngs.sh setup`. It looks like the setup process may have failed for some reason (it can happen sometimes if anaconda.org is overloaded during the day).

-Chris

**Comment by jrotieno** [comment]
Oh, I see. Will try that tomorrow at work and report back. It's 11pm here in Kenya and have no connection in the house...just have data for the phone! Many thanks.

**Comment by jrotieno** [comment]
Still not downloading/installing the viral-ngs directory after several attemps.

**Comment by tomkinsc** [comment]
Hi James,
Give the latest version of the script a try: 
https://raw.githubusercontent.com/broadinstitute/viral-ngs/master/easy-deploy-script/easy-deploy-viral-ngs.sh
It turns out some debug lines remained in the script before we had automated testing on it, and they were preventing setup from proceeding to completion. I've removed them, so hopefully all should be well.

**Comment by jrotieno** [comment]
Hi Tom,
The script proceeded to completion. I'll test the pipeline with the assemblies successfully completed on DnaNexus.
Many thanks.

**Comment by tomkinsc** [comment]
Great, glad to hear it. Closing this issue.
