### ISSUE TITLE
ktUpdateTaxonomy.sh fails when run outside krona dir

### ISSUE THREAD

**Issue by biocyberman** [broadinstitute/viral-ngs#569]
I was reading the documentation from this: http://viral-ngs.readthedocs.io/en/latest/install.html
I successfully installed the viral-ngs environment. However, the last step where it instructs about updating taxonomy database, I failed. I found out that I have to run the command inside krona directory, for my case it is at: `$HOME/bin/opt/anaconda/envs/viral-ngs-env/opt/krona/`

So I would suggest update the script or the documentation.

**Comment by tomkinsc** [comment]
Did you have the viral-ngs conda environment active (`source activate viral-ngs-env`) when you called `ktUpdateTaxonomy.sh`? If so, you may want to open an Issue for the krona problem [on the bioconda repository](https://github.com/bioconda/bioconda-recipes/issues/new), since that's where the krona dependency comes from.

**Comment by biocyberman** [comment]
Yes I do. Submitted a PR.

**Comment by tomkinsc** [comment]
Nice, thanks!
