### ISSUE TITLE
How to run my dev version?

### ISSUE THREAD

**Issue by biocyberman** [broadinstitute/viral-ngs#576]
I made the following changes for on my local git repo in order to use the refinement for single end data. I then overwrote the files in the conda environment with these files. This however, does not work because of version verification mechanism (which is a good thing). I don't want to setup vagrant and dev enronment yet. How do I replace the one I installed with `conda` with my local git repo?

```diff
diff --git a/assembly.py b/assembly.py
index 879eef4..df72898 100755
--- a/assembly.py
+++ b/assembly.py
@@ -682,7 +682,8 @@ def refine_assembly(
     JVMmemory=None,
     threads=1,
     gatk_path=None,
-    novoalign_license_path=None
+        novoalign_license_path=None,
+        single=False
 ):
     ''' This a refinement step where we take a crude assembly, align
         all reads back to it, and modify the assembly to the majority
@@ -720,7 +721,7 @@ def refine_assembly(
         # Novoalign reads to self
         novoBam = util.file.mkstempfname('.novoalign.bam')
         min_qual = 0 if keep_all_reads else 1
-        novoalign.execute(inBam, inFasta, novoBam, options=novo_params.split(), min_qual=min_qual, JVMmemory=JVMmemory)
+        novoalign.execute(inBam, inFasta, novoBam, options=novo_params.split(), min_qual=min_qual, JVMmemory=JVMmemory, single=single)
         rmdupBam = util.file.mkstempfname('.rmdup.bam')
         opts = ['CREATE_INDEX=true']
         if not keep_all_reads:
@@ -849,6 +850,14 @@ def parser_refine_assembly(parser=argparse.ArgumentParser()):
         help='A path to the novoalign.lic file. This overrides the NOVOALIGN_LICENSE_PATH environment variable. (default: %(default)s)'
     )
     parser.add_argument('--threads', default=1, help='Number of threads (default: %(default)s)')
+    parser.add_argument(
+        "--single",
+        help="""Single end mode, for iontorrent data""",
+        default=False,
+        action="store_true",
+        dest="single"
+    )
+
     util.cmd.common_args(parser, (('loglevel', None), ('version', None), ('tmp_dir', None)))
     util.cmd.attach_main(parser, refine_assembly, split_args=True)
     return parser
@@ -1488,3 +1497,4 @@ def full_parser():
 
 if __name__ == '__main__':
     util.cmd.main_argparse(__commands__, __doc__)

diff --git a/tools/novoalign.py b/tools/novoalign.py
index c301e9a..5fc05bb 100644
--- a/tools/novoalign.py
+++ b/tools/novoalign.py
@@ -76,7 +76,7 @@ class NovoalignTool(tools.Tool):
             raise ValueError('input file %s must end with .fasta' % fasta)
         return fasta[:-6] + '.nix'
 
-    def execute(self, inBam, refFasta, outBam, options=None, min_qual=0, JVMmemory=None):    # pylint: disable=W0221
+    def execute(self, inBam, refFasta, outBam, options=None, min_qual=0, JVMmemory=None, single=False):    # pylint: disable=W0221
         ''' Execute Novoalign on BAM inputs and outputs.
             If the BAM contains multiple read groups, break up
             the input and perform Novoalign separately on each one
@@ -111,7 +111,8 @@ class NovoalignTool(tools.Tool):
                     rgid=rg,
                     options=options,
                     min_qual=min_qual,
-                    JVMmemory=JVMmemory
+                    JVMmemory=JVMmemory,
+                    single=single
                 )
                 if os.path.getsize(tmp_bam) > 0:
                     align_bams.append(tmp_bam)
@@ -126,7 +127,7 @@ class NovoalignTool(tools.Tool):
             for bam in align_bams:
                 os.unlink(bam)
 
-    def align_one_rg_bam(self, inBam, refFasta, outBam, rgid=None, options=None, min_qual=0, JVMmemory=None):
+    def align_one_rg_bam(self, inBam, refFasta, outBam, rgid=None, options=None, min_qual=0, JVMmemory=None, singgle=False):
         ''' Execute Novoalign on BAM inputs and outputs.
             Requires that only one RG exists (will error otherwise).
             Use Picard to sort and index the output BAM.
@@ -177,7 +178,10 @@ class NovoalignTool(tools.Tool):
         tmp_sam = util.file.mkstempfname('.novoalign.sam')
         tmp_sam_err = util.file.mkstempfname('.novoalign.sam.err') 
```

**Comment by biocyberman** [comment]
After having some further hacking of viral-ngs code and playing around with versions of dependencies I could run the refine_assembly subcommand :) I also attempted to setup a proper dev environment with `vagrant` and `ansible`, but still haven't got it fully running. I hope to have time to play more with it.

**Comment by biocyberman** [comment]
While waiting for this, I downloaded the recipe from bionconda, modified it for my dev version, and installed the package offline. This approach requires knowledge about conda packaging. It's not difficult but still some extra work.

**Comment by tomkinsc** [comment]
If you're not changing the version of any tools used by viral-ngs, the easiest way to make changes to viral-ngs is to install the [conda package](https://bioconda.github.io/recipes/viral-ngs/README.html), clone this repository, and then call the files within the local clone with full/relative path prefix (ex. `./interhost.py`). For changes that alter tool versions, building the conda recipe as you did is one path. I'd  suggest instead: create a new conda environment and instal all of the dependencies listed in the [viral-ngs recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/viral-ngs/meta.yaml) (excluding the viral-ngs package itself). From there individual tools can be upgraded to downgraded within the active conda environment to match changes in the viral-ngs `tools/` scripts. If the packages are installed as version-pinned dependencies of the viral-ngs conda package (i.e. installed via `conda install viral-ngs`), attempts to upgrade them will fail as it sounds like you discovered.

The conda deployment workflow is actually in flux right now, since the new bioconda build system [cannot handle](https://github.com/bioconda/bioconda-recipes/pull/3531) a package as large as viral-ngs (including all of its dependencies). It's likely that we will soon push viral-ngs conda packages to a [separate channel](https://anaconda.org/broad-viral). The automation for that is still in flux, but it's likely the dependencies for the recipe will be stored in this repository via something like [`requirements-conda.txt`](https://github.com/broadinstitute/viral-ngs/blob/master/requirements-conda.txt).

It sounds like you're up and running though with a development install of viral-ngs? If so, I'll close this issue.

**Comment by biocyberman** [comment]
So the main point of making a dedicated conda environment is that we can upgrade/downgrade dependencies without messing up with other packages which may share some common dependencies?

I didn't know the limitation of bioconda as you said. But IMHO a separate channel is the last resort because version conflicts with other conda channel.  
 
Yes basically I got the hang of how to test drive my dev version.

**Comment by tomkinsc** [comment]
Right, a separate conda environment will help to ensure there aren't any version conflicts. It also makes it easier to export and import project-specific package lists.

A separate conda channel is not especially limiting in this case because the dependencies for viral-ngs will still be sourced from bioconda; only viral-ngs will be separate. Channel precedence for installing viral-ngs will use our channel first for viral-ngs, then `bioconda` for bio-specific dependencies, `conda-forge` for generic packages, and `defaults` for all remaining. Keeping viral-ngs in bioconda would be ideal, but with the new container-based build system it does not seem like it will be possible.

**Comment by yesimon** [comment]
If you're using `viral-ngs-deploy` to manage your viral-ngs installation, there a branch in progress that supports git-based viral-ngs installs in concordance with dependent conda package versioning: https://github.com/broadinstitute/viral-ngs-deploy/pull/13

The mechanism is by specifying env var `$INSTALL_PATH` to be the directory of the git based viral-ngs installation with the ultimate command being something like:

`env INSTALL_PATH=<install_dir> easy-deploy-viral-ngs.sh setup-git`

**Comment by biocyberman** [comment]
@tomkinsc I do not have experience regarding this, but it maybe an workaround: build viral-ngs conda package somewhere outside bionconda server, even though the build process still pull bioconda dependencies. And then the bioconda recipe is just to pull the built package into place on bioconda channel for distribution.

**Comment by tomkinsc** [comment]
@biocyberman: Yes, exactly, that's the plan! :) I started down that path yesterday and the goal is for our automated testing service, Travis, to build and push new releases to the broad-viral conda channel whenever we tag a new version. It will have the added benefit of automating our distribution process, where previously I would have to manually submit PRs to bioconda. We can also trigger builds of the Docker container automatically this way too. It'll be better once it is in place, but I'd like to consolidate our dependencies such that the recipe sources from the package lists we already have and we don't need to maintain lists in several places. It's ongoing.

**Comment by biocyberman** [comment]
Nice to hear :) Keep up the good work. I like `viral-ngs` much better than other repos that aim the same thing, but poor implementation.
