### ISSUE TITLE
error "dyld: Library not loaded: @rpath/libintl.9.dylib"

### ISSUE THREAD

**Issue by ekamau** [broadinstitute/viral-ngs#676]
I have been trying to run the snakefile pipeline but I keep getting this error about a dynamic library. I quite don't understand where the problem is; have tried in vain to fix it, even uninstalling and re-installing conda but can’t seem to fix it.

```
dyld: Library not loaded: @rpath/libintl.9.dylib
 Referenced from: /Users/ekamau/miniconda2/envs/viral-ngs-env/bin/gnu-getopt
 Reason: image not found
Terminating…
```

Any ideas? someone? thanks!

OS X Yosemite v10.10.5
happens when I run the 'snakemake' command
attached output from ‘conda list’ command (.txt)

[conda-list.txt](https://github.com/broadinstitute/viral-ngs/files/1336956/conda-list.txt)

**Comment by tomkinsc** [comment]
This issue continues an email conversation out of band. 

Thanks for posting the output of `conda list`. I don't see the viral-ngs dependencies included; are you using a separate conda environment for viral-ngs? If so, could you please activate it and then post the output of `conda list` again? If you are using the [easy-deploy script](https://github.com/broadinstitute/viral-ngs-deploy/tree/master/easy-deploy-script) (recommended), loading the environment via `source ./easy-deploy-viral-ngs.sh load` will also activate the isolated conda environment used for viral-ngs.

**Comment by tomkinsc** [comment]
I wonder if that problem with BMTagger is related to the symlink change; not sure the dylib you symlinked to is ABI compatible. 

Looking into this a bit more, `viral-ngs` depends on the package `gnu-getopt`, which in turn depends on `gettext`, which depends on `libintl`. A broken build of `gettext` (0.19.8) [was released on conda-forge with a incompatible newer libintl](https://github.com/conda-forge/gettext-feedstock/issues/4) which may have resulted in a broken build of `gnu-getopt` on bioconda. A corrected version of `gettext`, 0.19.8.1, is now on conda-forge. In attempt to resolve the issue in viral-ngs, I opened [a pull request](https://github.com/bioconda/bioconda-recipes/pull/6157) to rebuild `gnu-getopt`, and pull in the fixed `gettext`. I also [opened a PR](https://github.com/conda-forge/staged-recipes/pull/4063) to add `gnu-getopt` to `conda-forge`, which is where the package should really be (since it is generic and not bio-specific).

Once the pull requests have been merged in and the updated packages are available (not yet, but I'll let you know), you should be able to update to the newest versions via:
`conda update gettext gnu-getopt`

Make sure this is the channel precedence in your `~/.condarc` file:
```
channels:
  - broad-viral
  - bioconda
  - r
  - conda-forge
  - defaults
```

**Comment by ekamau** [comment]
Great. thanks. 

Yes - I realised yesterday this went back to gnu-getopt & gettext. So I manually updated these (via ports & conda) and had to point/set the symbolic link in the viral ngs env to these newer versions. 
Please let me know when you make updates.

And yes, that's the channel precedence I have, I'd think it stays that way since it's the order you install them. 

*I am a biologist (minimal computational acumen), debugging can be quite frustrating but I am getting there slowly.

thanks.

**Comment by tomkinsc** [comment]
Ok, the updated `gnu-getopt` is now [on bioconda](https://anaconda.org/bioconda/gnu-getopt/files) (the conda-forge build is still pending). Give the update command a try:
`conda update gettext gnu-getopt`

This should hopefully result in conda asking you to update to the following builds (gettext 0.19.8.1-0, and gnu-getopt 1.1.6-4):
```
The following packages will be UPDATED:

    gettext:    0.18.3-1 bioconda --> 0.19.8.1-0 conda-forge
    gnu-getopt: 1.1.6-2  bioconda --> 1.1.6-4    bioconda

Proceed ([y]/n)?
```

**Comment by ekamau** [comment]
Super!

Fixed the bmtagger error; I had mis-labelled the paths to the depletion databases ... (who knew!)
The pipeline is running now, no errors so far;
Will update the gnu-getopt once it's done.

thanks!

**Comment by dpark01** [comment]
@ekamau I'll close this for now, and please feel free to open up a new one for any new issues you encounter
