### ISSUE TITLE
make lastal databases ephemeral

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#686]
Currently, in the snakemake-based workflow (including staging down database files from the cloud), we are storing all of the `lastal` generated database files (bck, des, prj, sds, ssp, suf, tis) in permanent storage and pulling them all down. Even when not pulled from the cloud, we maintain the full set of files in persistent network storage in the `config["lastal_ref_db_dir"]`.

From a user interaction point of view, I'm inclined to make this behave more like the DNAnexus UI, where the user provides a `fasta` file, and all lastal database files are generated on the fly, for each execution, and are ephemeral / never persisted anywhere. A few reasons:

 - it could be one, easy to understand file, instead of a whole bunch of opaque ones
 - it turns out that creating the lastal db files from the fasta is actually quite quick (seems to be less than one minute for typical LASV inputs) so there isn't much of an efficiency reason to save them
 - it seems the binary index formats are changing between each version of the `lastal` tool itself, leading to more things that could go wrong should we choose to update the tool on someone

I propose having the snakemake rules take a single fasta file as input for the lastalDb, modify the `filter_lastal_bam` command to do the same, and have it build and store in an ephemeral tmp_dir. Alternatively keep the CLI the same, but have the snakemake rule do what the DNAnexus applet is doing (invoke `lastal_build_db` and `filter_lastal_bam` in succession, while making sure the db doesn't go to network storage).

Thoughts?

**Comment by tomkinsc** [comment]
We have a snakemake rule, [`build_lastal_db`](https://github.com/broadinstitute/viral-ngs/blob/master/pipes/rules/ncbi.rules#L49), to build a lastal db from a single fasta input file. The fasta file is downloaded on the fly based on the accessions in the file `config["accessions_file_for_lastal_db_build"]`. The only thing stopping the database from being ephemeral is wrapping the db files with Snakemake's [`temp() flag`](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#protected-and-temporary-files), and removal of `objectify_remote()` from the [`filter_to_taxon`](https://github.com/broadinstitute/viral-ngs/blob/master/pipes/rules/hs_deplete.rules#L58) rule (since if the files exist, even remotely, they will be downloaded/used rather than built by the upstream `build_lastal_db` rule).

**Comment by notestaff** [comment]
Maybe just move it from root project dir to tmp/lastal_db?

**Comment by dpark01** [comment]
@notestaff `tmp/` is not ephemeral though, in most Broad_UGER setups, it's on NFS and is not truly temporary (DNAnexus calls this directory "intermediates").

@tomkinsc what do you think about the general idea / UI though of not persisting the indexes for lastal? (at the moment, I'm only proposing the lastal dbs because I'm not yet familiar with how long it takes to build blast, bmtagger, and other database index files).

For various reasons, I've been playing a little with `last` v876 (mostly because bioconda doesn't have a python 3.6 macos build for v719). No real end to end difference, but the index files are different, so the unit test that does a binary file comparison of the outputs of `build_lastal_db` does fail, but I think that doesn't bother me...

**Comment by tomkinsc** [comment]
It probably makes sense to build the lastal DB on the fly; for our input size it's probably faster to download a fasta file and build than it is to download a pre-built DB.
