### ISSUE TITLE
snakemake pipeline fail

### ISSUE THREAD

**Issue by jb013b** [broadinstitute/viral-ngs#745]
I am writting because I am having some difficulty with the snakemake pipeline. I have attached the log file as well as a copy of the command and the output to terminal.

briefly
installed viral ngs pipeline via easy-deploy script
GATK is registered and functioning
viral-ngs is working based upon pytest

I edited the config file (downloading the associated databases). To run the file names for several of the data sets needed to be changed. ex. .../hybsel_probe_adapters/hybsel_probe_adapters.fasta to .../hybsel_probe_adapters/.fasta.

this allowed snakemake -np to run without an error

I am running one raw .bam file, this contains all the reads from one barcode in the file, no depletion.
This is illumina sequencing run with chikungunya virus and vero cells (non human primate).

Also can you provide a link how to properly format the files for:
Text file containing sequencer flowcell metadata

[config.txt](https://github.com/broadinstitute/viral-ngs/files/1592150/config.txt)

[snakemake_test1.txt](https://github.com/broadinstitute/viral-ngs/files/1592133/snakemake_test1.txt)
[2017-12-28T145639.601565.snakemake.log](https://github.com/broadinstitute/viral-ngs/files/1592135/2017-12-28T145639.601565.snakemake.log)

**Comment by tomkinsc** [comment]
The Snakemake error looks like it is caused by the input bam file crashing pysam (one of the underlying dependencies of viral-ngs). This is perhaps related to how the bam file was generated, or maybe this one file happens to have a bad header. The relevant section of the log is here:
```
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::bam_hdr_read] Truncated BAM header
Traceback (most recent call last):
  File "bin/taxon_filter.py", line 728, in <module>
    util.cmd.main_argparse(__commands__, __doc__)
  File "/home/jb013b/NGS/viral-ngs-etc/conda-env/opt/viral-ngs-1.19.0/util/cmd.py", line 212, in main_argparse
    ret = args.func_main(args)
  File "bin/taxon_filter.py", line 96, in main_deplete_human
    with pysam.AlignmentFile(args.inBam, 'rb', check_sq=False) as bam:
  File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 654, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file `data/00_raw/parent-CHIKV_S8_CHIKV_MMUL_unmapped.bam` does not have valid header
```
You may want to take a look at the file header with `samtools view -H` to see if any problems stand out. A simple test you can run in isolation would be to try to open the bam file in a simple python script using pysam (with the viral-ngs environment active). Something like:
```
import pysam
bamfile = pysam.AlignmentFile("ex1.bam", "rb", check_sq=False)
```

The format of the text file containing sequencer flowcell metadata is described here:
https://viral-ngs.readthedocs.io/en/latest/pipeuse.html#starting-from-illumina-bcl-directories
It's a TSV file with the following structure:
```
flowcell        lane    barcode_file    bustard_dir     max_mismatches
H32G3ADXY       1       /path/to/barcodes.txt    /path/to/illumina/run/directory/run_BH32G3ADXY 1
```

**Comment by jb013b** [comment]
Thank you.
Yes there was a problem with the uBAM file. I am now trying to use picard FastqToSam to generate new BAM files.
