### ISSUE TITLE
Ensure BWA-based depletion is tolerant of unpaired reads

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#779]
BWA-based depletion in taxon_filter.py appears to work fine on purely paired input, but may not be tolerant of input composed of single-end reads or a mix of both.

Example of a possible failure (or it might be due to something else): https://platform.dnanexus.com/projects/F95x4j80Z3ygZgQB0v92Gfyz/monitor/analysis/F9k7XP00Z3ypbB5pF5xzgx2q

**Comment by dpark01** [comment]
On a related note, the BAM output of BWA-based depletion has elements that suggest it is aligned (it has `SO:coordinate` instead of `SO:queryname` and it has a bunch of `@SQ` lines in the header) even though all of its entries are unaligned. It could probably use a pass of RevertSam on the output.

**Comment by dpark01** [comment]
@tomkinsc notes that BWA 0.7.11 introduced a new `-p` flag to bwa mem (we have 0.7.15):
> Smarter option `-p`. Given an interleaved FASTQ stream, old bwa-mem identifies
>  the 2i-th and (2i+1)-th reads as a read pair. The new verion identifies
> adjacent reads with the same read name as a read pair. It is possible to mix
> single-end and paired-end reads in one FASTQ.

This means we don't have to partition the input prior to calling BWA, and can simplify the invocation by piping `samtools bam2fq` straight to `bwa mem -p`.

**Comment by dpark01** [comment]
Though, on another note, for the sake of depletion, if one read maps, we should probably be tossing its mate as well even if that didn't map (this might just be a matter of adding more bits to the samtools filter bitmask).

While also ensuring that single-end reads are treated fairly in this process (ie, unmapped singles are not just discarded for being single). This will require some new unit tests.

**Comment by tomkinsc** [comment]
We currently specify the flag setting of `-f0x4`, which translates to "only output reads flagged as unmapped [to depletion sequence]". If we add 8, and pass `-f0x12` that should (I think?) only output pairs where both reads are in the pair are unmapped. Singletons will probably be omitted from the output if we add 8. Maybe we should also pass `-F0x256` to never omit reads flagged as "not primary alignment". So, `samtools view -f0x12 -F0x256`. For only singletons: `-F0x1 -f0x4` (read is not paired, and read is unmapped).

Not sure we can get both unmapped pairs and unmapped singletons in the same call, since `-f` (include) is bitwise & and `-F` (exclude) is bitwise |.

**Comment by dpark01** [comment]
One other possible route (may not be preferable, but would work) would be to do what our other depletion tools do and use bwa to dump a read ID list and use Picard FilterSamReads to go straight from input bam to output bam. This would obviate the need for a RevertSam cleanup at the end and has the nice feature of behaving the way we want it to behave for paired, single, or a mix of both kinds of reads (we've tested this already). FilterSamReads removes any read who's ID matches those given in the input list, meaning that it'll remove both of a pair even if only one of them was mapped by the tool, but it won't require pairs (unpaired reads will still pass through on their own merits).

Would be a little sad to go this way, but at least FilterSamReads isn't terribly slow, and who knows, maybe it's not much slower than RevertSam & samtools `-f` / `-F`?

**Comment by tomkinsc** [comment]
Maybe we should pass the bwa output bam to Picard `FilterSamReads` and try the `JAVASCRIPT_FILE` option to specify our include/exclude logic, that way we would not have to prepare a read ID list.

**Comment by dpark01** [comment]
Interesting... on one hand, I'm sure the javascript parsing isn't speedy, on the other hand, I bet that could mean we could do this entire process with no temp files at all..
`samtools bam2fq in.bam | bwa mem -p | picard FilterSamReads | picard RevertSam > out.bam`
Though we'd have to be careful about how much memory we allocate to each of the two Javas...

**Comment by tomkinsc** [comment]
We could also use the `invert_filter` option of `bwa.Bwa().filter_sam_on_alignment_score()`, but it is not fast.

**Comment by dpark01** [comment]
BTW creating a read ID list isn't hard--all the other depletion tools do this by piping output and pulling the relevant column and just keeping that, minimizing the amount of I/O to disk or temp space usage. And in this scenario, you could just implement the flag filter yourself in python prior to writing that ID to the temp txt file.

**Comment by tomkinsc** [comment]
We aren't piping from bmtagger since it returns a matches list, and blast returns a tabular output of reads exceeding the threshold, which we do pipe. For bwa wouldn't we have to pipe the entire sam output (not just matches, since `-T`[ has no effect](https://github.com/lh3/bwa/issues/133#issuecomment-313406480) on paired-end mappings) and examine that to get the read list? At that point it wouldn't be much more trouble to do the read filtering in Python, which would be slow. 

The javascript option for FilterSamReads may not actually be too slow. Browsers and node.js have directed significant attention to improving JS performance, so Nashorn (the Java JS engine based on the JVM) is not so far from V8 in performance.

**Comment by yesimon** [comment]
The best way would be to take a strict subset iterating over the original bam file like in my other branch: https://github.com/broadinstitute/viral-ngs/compare/sy-diamond-leftover#diff-9cb3a251701988ee894d3ff675fcb687R1189. This is fine because bwa outputs in the exact same order as the input.

**Comment by yesimon** [comment]
Regarding the filtering flags for the paired only scenario, maybe it's best to only filter out the confident proper pairs `-F 0x2`. This will leave in some discordant and low alignment score human reads but it's better to be cautious rather than overeager when depleting. From my experience `bwa mem` does output many low quality hits with `AS` in the 20-30s which is often spurious, but rarely marks them as a proper pair.

**Comment by tomkinsc** [comment]
Here are some quick run times of a simple bakeoff of `samtools` vs. `picard FilterSamReads` (with JS filter script) vs. `bamtools filter` (with json filter script) emitting only reads with a flag bit of `0x4` set (same input of 5M reads for each):
```
samtools 16s
bamtools 35s
picard FilterSamReads 48s
```

**Comment by tomkinsc** [comment]
The [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) cautions:
>Bit `0x4` is the only reliable place to tell whether the read is unmapped. If `0x4` is set, no assumptions can be made about RNAME, POS, CIGAR, MAPQ, and bits `0x2`, `0x100`, and `0x800`.

**Comment by dpark01** [comment]
So what's your current thinking: `samtools bam2fq | bwa mem | samtools view -F | picard RevertSam`?
