### ISSUE TITLE
iSNV per-sample processing pipeline (step 1)

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#88]
After V-Phaser2 produces iSNV calls, a few filtration and markup steps should be performed. Create a new command in intrahost.py (maybe something like "vphaser_one_sample") that looks like the following:

- Input: a single BAM file, representing reads from one sample, mapped to its own consensus assembly. It may contain multiple read groups and libraries.
- Output: a single tabular text file, similar to V-Phaser's output format, but with some additional columns added (# libraries, chi-sq for library discordance).

Steps:

1. Call V-Phaser2: BAM -> text file with iSNV calls

2. Hard filtering of iSNVs based on read counts and strand bias on a per-library basis. Use pysam to reach into the original BAM file to query the read pileup at each iSNV position. At each position, count up how many reads are on a given strand and library. Toss out the counts for any library that fails the strand bias / minimum read count criteria. Toss out iSNVs that have no libraries left at this point. Pass any remaining iSNVs downstream along with their per-library read counts.

3. For each iSNV, add columns that denote the number of libraries that survived the above filters and a chi-sq or fisher's exact test score for the agreement of allele frequencies across libraries (for iSNVs that have > 1 library).

**Comment by dpark01** [comment]
#82 will need to be fixed before this will work...

**Comment by iljungr** [comment]
Don't implement this until we resolve whether to use the alternative approach suggested in dpark's 2/19 email:

Input file: BAM aligned to self, including all reads, all libraries, for a given sample

1. Break up big BAM into per-library BAMs, then run V-Phaser on each. This is a bit cleaner than what we did over the summer in that at least all of the outputs are guaranteed to be in the same coordinate space (because they're aligned to the same "self" consensus assembly. However, they will not be guaranteed to be talking about the same alleles (because the majority and minority alleles may differ per-library) and they may not report the same set of positions in the output (because a position might not be variable in one library). However, in theory, the union of all positions (and alleles at each position) should equal the set of positions (and alleles) described by running V-Phaser once on the big BAM.

2. Perform strand-bias hard filtering per library.

3. Merge per-library V-Phaser outputs together so that we have per-library per-allele per-strand counts at each position. This will not require coordinate remapping. But it will require allele re-ordering. This will require a little more thought to know whether this will be straightforward, or will sometimes have weird cases too...

4. Calculate library-bias statistics and produce a single output table for the sample, in the sample's own coordinate space.

**Comment by dpark01** [comment]
Okay, here's the **modified** marching orders, modified from the top entry on this issue:

After V-Phaser2 produces iSNV calls, a few filtration and markup steps should be performed. Create a new command in intrahost.py (maybe something like "vphaser_one_sample") that looks like the following:

- Input: a single BAM file, representing reads from one sample, mapped to its own consensus assembly. It may contain multiple read groups and libraries.

- Output: a single tabular text file, similar to V-Phaser's output format, but with some additional columns added (sequence/chrom name, # libraries, chi-sq for library discordance).  This should be a tab-separated text file with no header row and the following fields:

  - CHROM, Ref_Pos, Var, Cons, Strd_bias_pval, Type, Var_perc, N_LIBRARIES, LIB_BIAS_PVAL, SNP_or_LP_Profile1, SNP_or_LP_Profile2, ...

Steps:

1. Call V-Phaser2: BAM -> text file with iSNV calls

2. Hard filtering of iSNVs based on read counts and strand bias ~~on a per-library basis~~ on the total read set. ~~Use pysam to reach into the original BAM file to query the read pileup at each iSNV position. At each position, count up how many reads are on a given strand and library.~~ Toss out the counts for any allele that fails the strand bias / minimum read count criteria. Toss out iSNVs that have no alleles left at this point. Pass any remaining iSNVs downstream ~~along with their per-library read counts~~.

3. For each iSNV, add columns that denote the number of libraries that survived the above filters and a chi-sq or fisher's exact test score for the agreement of allele frequencies across libraries (for iSNVs that have > 1 library). **But instead of populating them with data, just leave them blank for now!** (we'll implement these calculations later when we have more time)

None of the above should require any "reaching into the BAM file" anymore. We'll handle that stuff later.

In terms of implementation, my thought would be that the actual script command would look something like:

1. run vphaser2.iterate on BAM file
2. call intrahost.filter_strand_bias on iterator
3. call intrahost.calc_library_bias on iterator (some new method that doesn't do much)
4. for each isnv remaining, output to tab file
