### ISSUE TITLE
Migrate Kraken -> Kraken 2

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#908]
Kraken v1 is no longer supported. We should change our pipeline to use Kraken v2.
https://ccb.jhu.edu/software/choosing-a-metagenomics-classifier/
@yesimon: Can you comment on whether there are any issues blocking us from doing so? Will we need a modified build for it as you created for v1?

**Comment by yesimon** [comment]
I wouldn't recommend migrating to Kraken2, because it fundamentally trades-off lower classification performance for significant improvements in runtime and computational requirements. The proper migration would probably be Kraken -> KrakenUniq.

In their own FAQ section:
> In cases where false positives can be detrimental to the overall interpretation of the results (e.g. in pathogen identification/diagnoses), KrakenUniq is best suited to help filter false positives and validate classification.
However, in cases where users are limited by speed/memory, we suggest Kraken 2. Kraken 2 uses 6-7x less memory than Kraken 1, builds databases 4x faster than Kraken 1 and KrakenUniq and processes sample data in 5-6x less time.
